C  HARYDAT.H - HYDROLOGY MODEL GRID-ELEMENT ARRAY NUMBERS

C  CODE HISTORY:

C  JOHN WHEELER     4/29/97    ALPHA VERSION
C  JOHN WHEELER     8/29/98    MODULAR VERSION

C*********************************************************************
      INTEGER N_POIL,N_PWAT,N_COIL,N_DUNK,N_COILN,N_CWATN,
     &     N_RELPRM,N_DPCSW,N_COF,N_RESID,N_POILN,N_VEL,N_VMO,N_VMW,
     &     N_DDENS

      COMMON /HGEA/ N_POIL,N_PWAT,N_COIL,N_DUNK,N_COILN,N_CWATN,
     &     N_RELPRM,N_DPCSW,N_COF,N_RESID,N_POILN,N_VEL,N_VMO,N_VMW,
     &     N_DDENS

C*********************************************************************

C  N_POIL = GRID-ELEMENT ARRAY NUMBER FOR OIL PRESSURE, PSI (REAL*8)

C  N_PWAT = GRID-ELEMENT ARRAY NUMBER FOR WATER PRESSURE, PSI (REAL*8)

C  N_COIL = GRID-ELEMENT ARRAY NUMBER FOR OIL CONCENTRATION, LB/CU-FT (REAL*8)

C  N_DUNK  = GRID-ELEMENT ARRAY NUMBER FOR LINEAR SOLUTION
C           DUNK(I,J,K,1) ==> CHANGE IN OIL PRESSURE, PSI (REAL*8)
C           DUNK(I,J,K,2) ==> CHANGE IN OIL CONCENTRATION, LB/CU-FT (REAL*8)
C         ALSO
C           DUNK(I,J,K,1) ==> OIL DENSITY, LB/CU-FT
C           DUNK(I,J,K,2) ==> WATER DENSITY, LB/CU-FT

C  N_COILN = GRID-ELEMENT ARRAY NUMBER FOR OIL CONCENTRATION AT BEGINNING
C            OF TIME STEP , LB/CU-FT (REAL*8)

C  N_CWATN = GRID-ELEMENT ARRAY NUMBER FOR WATER CONCENTRATION AT BEGINNING
C            OF TIME STEP , LB/CU-FT (REAL*8)

C  N_RELPRM = GRID-ELEMENT ARRAY NUMBER FOR RELATIVE PERMEABILITY DATA
C             (REAL*8)
C             RELPRM(I,J,K,1) = OIL RELATIVE PERMEABILITY
C             RELPRM(I,J,K,2) = DERIVATIVE OIL RELATIVE PERMEABILITY WRT Sw
C             RELPRM(I,J,K,3) = WATER RELATIVE PERMEABILITY
C             RELPRM(I,J,K,4) = DERIVATIVE WATER RELATIVE PERMEABILITY WRT Sw

C  N_DPCSW  = GRID-ELEMENT ARRAY NUMBER FOR DERIVATIVE OF Pc WRT Sw, PSI
C             (REAL*8)

C  N_COF  = GRID-ELEMENT ARRAY NUMBER FOR JACOBIAN COEFFICIENTS (REAL*4)
C           COF(I,J,K,N,L,M)
C           L=1 ==> OIL BALANCE EQUATION
C           L=2 ==> WATER BALANCE EQUATION
C           M=1 ==> OIL PRESSURE COEFFICIENT
C           M=2 ==> OIL CONCENTRATION COEFFICIENT
C           7 POINT TEMPLATE ($NUMCOF=7)
C           COF(I,J,K,1,L,M) ==> DIAGONAL
C           COF(I,J,K,2,L,M) ==> X-
C           COF(I,J,K,3,L,M) ==> X+
C           COF(I,J,K,4,L,M) ==> Y-
C           COF(I,J,K,5,L,M) ==> Y+
C           COF(I,J,K,6,L,M) ==> Z-
C           COF(I,J,K,7,L,M) ==> Z+

C  N_RESID= GRID-ELEMENT ARRAY NUMBER FOR RESIDUALS (REAL*8)
C           RESID(I,J,K,N) ==> RESIDUAL OF EQUATION N
C           N=1 ==> OIL BALANCE EQUATION
C           N=2 ==> WATER BALANCE EQUATION

C  N_POILN = GRID-ELEMENT ARRAY NUMBER FOR OIL PRESSURE AT BEGINNING OF
C            TIME STEP , PSI (REAL*8)
