C  CODE HISTORY:        
C      THE IPARS TEAM          04/02/1997   FRAMEWORK
C      RICK DEAN               03/02/2001   INITIAL VERSION
C      SUNIL G. THOMAS         09/01/2007   THERMAL, DIFF-DISP AND CO2 APPS 
C**************************************************************************


C-------specify some commonly used constants
      REAL*8 ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, THREEHALF, SIXTH,
     &       SEVEN, EIGHT, NINE, TEN, TEN_P2, TEN_P3, HALF, TEMP_SPAN,
     &       TWOTHIRD, TENTH, THIRD, NINTH, SMALL, BIG, TEN_P15,
     &       TEN_M6, TEN_M10, TEN_P6, TEN_M8, TEN_M4, TEN_P10, TEN_M2,
     &       SQRT_2, GCON_STD, STDPRES, STDTEMP, STDWCP, RCPCV, PRA, 
     &       PRB, TRF, FT_TO_BBL, TEN_M3, TEN_M15, TEN_P4, CWKH, 
     &       BBL_TO_FT, PCHOR_MULT

      REAL*4 SZERO,SONE

C     FOLLOWING SET IN xisdat.df
      REAL*8 LBMOLE_TO_MCF,GASCON
      COMMON/CONSTANTS/LBMOLE_TO_MCF,GASCON

      PARAMETER (ZERO = 0.0D0)
      PARAMETER (SZERO = 0.0)
      PARAMETER (ONE = 1.0D0)
      PARAMETER (SONE = 1.0)
      PARAMETER (TWO = 2.0D0)
      PARAMETER (THREE = 3.0D0)
      PARAMETER (FOUR = 4.0D0)
      PARAMETER (FIVE = 5.0D0)
      PARAMETER (SIX = 6.0D0)
      PARAMETER (SEVEN = 7.0D0)
      PARAMETER (EIGHT = 8.0D0)
      PARAMETER (NINE = 9.0D0)
      PARAMETER (TEN = 10.0D0)
      PARAMETER (SQRT_2 = 1.41421356237310D0)

C-------special constants
      PARAMETER (STDPRES = 14.7D0)
      PARAMETER (STDTEMP = 60.0D0)
      PARAMETER (STDWCP = 0.9997D0)
      PARAMETER (RCPCV = 1.98589D0)
      PARAMETER (GCON_STD = 0.0069444D0)
      PARAMETER (PRA = .457235528921382D0)
      PARAMETER (PRB = .777960739038884D-1)
      PARAMETER (PCHOR_MULT = 0.016018D0)

      PARAMETER (TRF = 459.67D0)
      PARAMETER (SMALL = 1.0D-30)
      PARAMETER (BIG = 1.0D30)
      PARAMETER (FT_TO_BBL = .178107585530824D0)
      PARAMETER (CWKH = 0.0063282864D0)

C-------derived values
      PARAMETER (TENTH = ONE/TEN)
      PARAMETER (TEN_M2 = TENTH**2)
      PARAMETER (TEN_M3 = TENTH**3)
      PARAMETER (TEN_M4 = TENTH**4)
      PARAMETER (TEN_M6 = TENTH**6)
      PARAMETER (TEN_M8 = TENTH**8)
      PARAMETER (TEN_M10 = TENTH**10)
      PARAMETER (TEN_M15 = TENTH**15)
      PARAMETER (TEN_P2 = TEN**2)
      PARAMETER (TEN_P3 = TEN**3)
      PARAMETER (TEN_P4 = TEN**4)
      PARAMETER (TEN_P6 = TEN**6)
      PARAMETER (TEN_P10 = TEN**10)
      PARAMETER (TEN_P15 = TEN**15)
      PARAMETER (HALF = ONE/TWO)
      PARAMETER (THREEHALF = ONE+HALF)
      PARAMETER (THIRD = ONE/THREE)
      PARAMETER (TWOTHIRD = TWO/THREE)
      PARAMETER (SIXTH = ONE/SIX)
      PARAMETER (NINTH = ONE/NINE)
      PARAMETER (BBL_TO_FT = ONE / FT_TO_BBL)
