C  IARYDAT.H - BLACK OIL MODEL GRID-ELEMENT ARRAY NUMBERS

C  CODE HISTORY:

C  JOHN WHEELER     7/15/97    INITIAL VERSION
C  Joe Eaton        9/16/97    Checked out for black oil
C  JOHN WHEELER     9/30/99    REDUCED NUMBER OF ARRAYS

C*********************************************************************
       INTEGER N_POIL,N_PWAT,N_PGAS,N_OIL,N_GAS,N_POILN,N_OILN,
     &   N_WATN,N_GASN,N_SGASN,N_DUNK,N_TRNDAT,N_COF,N_RESID,
     &   N_SGAS,N_DGRO,N_TLAMB,N_VMO,N_VMW,N_VMG,N_VEL,N_RHO

      COMMON/IGEA/N_POIL,N_PWAT,N_PGAS,N_OIL,N_GAS,N_POILN,N_OILN,
     &   N_WATN,N_GASN,N_SGASN,N_DUNK,N_TRNDAT,N_COF,N_RESID,
     &   N_SGAS,N_DGRO,N_TLAMB,N_VMO,N_VMW,N_VMG,N_VEL,N_RHO

C*********************************************************************

C  N_POIL = GRID-ELEMENT ARRAY NUMBER FOR OIL PRESSURE, PSI (REAL*8)

C  N_PWAT = GRID-ELEMENT ARRAY NUMBER FOR WATER PRESSURE, PSI (REAL*8)

C  N_PGAS = GRID-ELEMENT ARRAY NUMBER FOR GAS PRESSURE, PSI (REAL*8)

C  N_OIL  = GRID-ELEMENT ARRAY NUMBER FOR OIL STOCK TANK VOLUME PER
C           UNIT PORE VOLUME (REAL*8)

C  N_GAS  = GRID-ELEMENT ARRAY NUMBER FOR GAS STOCK TANK VOLUME PER
C           UNIT PORE VOLUME (REAL*8)

C  N_POILN= GRID-ELEMENT ARRAY NUMBER FOR OIL PRESSURE AT TIME
C           LEVEL N, PSI (REAL*8)

C  N_OILN = GRID-ELEMENT ARRAY NUMBER FOR OIL STOCK TANK VOLUME PER
C           UNIT PORE VOLUME AT TIME LEVEL N (REAL*8)

C  N_WATN = GRID-ELEMENT ARRAY NUMBER FOR WATER STOCK TANK VOLUME PER
C           UNIT PORE VOLUME AT TIME LEVEL N (REAL*8)

C  N_GASN = GRID-ELEMENT ARRAY NUMBER FOR GAS STOCK TANK VOLUME PER
C           UNIT PORE VOLUME AT TIME LEVEL N (REAL*8)

C  N_SGASN = GRID-ELEMENT ARRAY NUMBER FOR GAS SATURATION AT TIME
C            LEVEL N (REAL*4)

C  N_DUNK  = GRID-ELEMENT ARRAY NUMBER FOR LINEAR SOLUTION (REAL*8)
C  BEFORE LINEAR SOLUTION:
C     DUNK(I,J,K,1) ==> OIL DENSITY, LB/BBL
C     DUNK(I,J,K,2) ==> WATER DENSITY, LB/BBL
C     DUNK(I,J,K,3) ==> GAS DENSITY, LB/BBL
C  AFTER LINEAR SOLUTION:
C     DUNK(I,J,K,1) ==> CHANGE IN OIL PRESSURE, PSI
C     DUNK(I,J,K,2) ==> CHANGE IN OIL STOCK TANK VOLUME PER UNIT PORE VOLUME
C     DUNK(I,J,K,3) ==> CHANGE IN GAS STOCK TANK VOLUME PER UNIT PORE VOLUME

C  N_TRNDAT = GRID-ELEMENT ARRAY NUMBER FOR TRANSMISSABILITY DATA (REAL*4)
C  TRNDAT(I,J,K,1) = DERIVATIVE OF OIL LAMBDA WRT OIL CONCENTRATION
C  TRNDAT(I,J,K,2) = DERIVATIVE OF OIL LAMBDA WRT OIL PRESSURE
C  TRNDAT(I,J,K,3) = DERIVATIVE OF OIL LAMBDA WRT GAS CONCENTRATION
C  TRNDAT(I,J,K,4) = DERIVATIVE OF WATER LAMBDA WRT OIL CONCENTRATION
C  TRNDAT(I,J,K,5) = DERIVATIVE OF WATER LAMBDA WRT OIL PRESSURE
C  TRNDAT(I,J,K,6) = DERIVATIVE OF WATER LAMBDA WRT GAS CONCENTRATION
C  TRNDAT(I,J,K,7) = DERIVATIVE OF GAS LAMBDA WRT OIL PRESSURE (3 PHASE)
C  TRNDAT(I,J,K,8) = DERIVATIVE OF GAS LAMBDA WRT OIL CONCENTRATION (3 PHASE)
C                  = DERIVATIVE OF OIL DENSITY WRT OIL CONCENTRATION (2 PHASE)
C  TRNDAT(I,J,K,9) = DERIVATIVE OF GAS LAMBDA WRT GAS CONCENTRATION (3 PHASE)
C                  = DERIVATIVE OF OIL DENSITY WRT GAS CONCENTRATION (2 PHASE)
C  TRNDAT(I,J,K,10) = DERIVATIVE OF WATER DENSITY WRT WATER PRESSURE
C  TRNDAT(I,J,K,11) = DERIVATIVE OF OIL DENSITY WRT OIL PRESSURE
C  TRNDAT(I,J,K,12) = DERIVATIVE OF GAS DENSITY WRT GAS PRESSURE (3 PHASE)
C  TRNDAT(I,J,K,13) = DERIVATIVE OF Ro WRT OIL PRESSURE (3 PHASE)
C  TRNDAT(I,J,K,14) = DERIVATIVE OF WATER PRESSURE WRT OIL PRESSURE
C  TRNDAT(I,J,K,15) = DERIVATIVE OF WATER PRESSURE WRT OIL CONCENTRATION
C  TRNDAT(I,J,K,16) = DERIVATIVE OF WATER PRESSURE WRT GAS CONCENTRATION
C  TRNDAT(I,J,K,17) = DERIVATIVE OF GAS PRESSURE WRT OIL PRESSURE (3 PHASE)
C  TRNDAT(I,J,K,18) = DERIVATIVE OF GAS PRESSURE WRT OIL CONCENTRATION (3 PHASE)
C  TRNDAT(I,J,K,19) = DERIVATIVE OF GAS PRESSURE WRT GAS CONCENTRATION (3 PHASE)

C  N_COF  = GRID-ELEMENT ARRAY NUMBER FOR JACOBIAN COEFFICIENTS (REAL*4)
C  COF(I,J,K,N,L,M)
C  L=1 ==> WATER BALANCE EQUATION
C  L=2 ==> OIL BALANCE EQUATION
C  L=3 ==> GAS BALANCE EQUATION
C  M=1 ==> OIL PRESSURE COEFFICIENT
C  M=2 ==> OIL CONCENTRATION COEFFICIENT
C  M=3 ==> GAS CONCENTRATION COEFFICIENT
C  7 POINT TEMPLATE ($NUMCOF=7)
C  COF(I,J,K,1,L,M) ==> DIAGONAL
C  COF(I,J,K,2,L,M) ==> X-
C  COF(I,J,K,3,L,M) ==> X+
C  COF(I,J,K,4,L,M) ==> Y-
C  COF(I,J,K,5,L,M) ==> Y+
C  COF(I,J,K,6,L,M) ==> Z-
C  COF(I,J,K,7,L,M) ==> Z+

C  N_RESID= GRID-ELEMENT ARRAY NUMBER FOR RESIDUALS (REAL*8)
C     RESID(I,J,K,L) ==> RESIDUAL OF EQUATION N
C     L=1 ==> OIL BALANCE EQUATION
C     L=2 ==> WATER BALANCE EQUATION
C     L=3 ==> GAS BALANCE EQUATION

C  N_SGAS = GRID-ELEMENT ARRAY NUMBER FOR GAS SATURATION, (REAL*4)

C  N_DGRO = GRID-ELEMENT ARRAY NUMBER FOR DISOLVED GAS/OIL RATIO, (REAL*8)

C  N_TLAMB = GRID-ELEMENT ARRAY NUMBER FOR LAMBDAS, (REAL*8)
C  TLAMB(I,J,K,1) ==> OIL LAMBDA
C  TLAMB(I,J,K,2) ==> WATER LAMBDA
C  TLAMB(I,J,K,3) ==> GAS LAMBDA

C  N_VEL= GRID-ELEMENT ARRAY NUMBER FOR VELOCITIES, (REAL*8)
C  VEL(I,J,K,IPHASE,IFACE)

C  N_PV = GRID-ELEMENT ARRAY NUMBER FOR PORE VOLUME (REAL*8)

C  N_PVN = GRID-ELEMENT ARRAY NUMBER FOR PORE VOLUME AT TIME LEVEL N (REAL*8)

C  N_CR = GRID-ELEMENT ARRAY NUMBER FOR ROCK COMPRESSIBILITY (REAL*8)

C  N_REFPRES = GRID-ELEMENT ARRAY NUMBER FOR REFERENCE PRESSURE (REAL*8)

C  N_PROP = ROCK MATERIAL PROPERTIES (LAME'S CONSTANTS (LAMBDA,MU), BIOT'S
C           CONSTANT AND ROCK DENSITY)

